-- PORT-09 CRM Phase 1
--
-- Adds the audit-trail and pending-payments primitives plus the lead /
-- quote / client field enrichments needed for the lead pipeline.
--
-- Compatible with PR-1 (lead unification) and PR-2 (numbering).

-- ==================== CrmActivityLog ====================

CREATE TABLE "CrmActivityLog" (
    "id"          TEXT NOT NULL,
    "tenantId"    TEXT NOT NULL,
    "entityType"  TEXT NOT NULL,            -- "lead" | "quote" | "reservation" | "invoice" | "payment"
    "entityId"    TEXT NOT NULL,
    "action"      TEXT NOT NULL,            -- "created" | "updated" | "status_changed" | "email_sent" | "payment_received" | "payment_failed" | "note_added" | "assigned" | "converted" | "lost"
    "actorId"     TEXT,                     -- userId; null for system actions (webhooks, cron)
    "actorName"   TEXT,
    "details"     JSONB,                    -- { oldStatus, newStatus, note, amount, ... }
    "createdAt"   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "CrmActivityLog_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "CrmActivityLog_tenantId_entityType_entityId_idx"
  ON "CrmActivityLog"("tenantId", "entityType", "entityId");
CREATE INDEX "CrmActivityLog_tenantId_createdAt_idx"
  ON "CrmActivityLog"("tenantId", "createdAt");

ALTER TABLE "CrmActivityLog"
  ADD CONSTRAINT "CrmActivityLog_tenantId_fkey"
  FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE CASCADE;

-- ==================== PendingPayment ====================

CREATE TABLE "PendingPayment" (
    "id"               TEXT NOT NULL,
    "tenantId"         TEXT NOT NULL,
    "quoteId"          TEXT,
    "reservationId"    TEXT,
    "clientName"       TEXT NOT NULL,
    "clientEmail"      TEXT,
    "clientPhone"      TEXT,
    "productName"      TEXT,
    "amountCents"      INTEGER NOT NULL,
    "dueDate"          TIMESTAMP(3),
    "reason"           TEXT,
    "status"           TEXT NOT NULL DEFAULT 'pending',  -- pending | reminded | paid | cancelled
    "paymentMethod"    TEXT,
    "paymentNote"      TEXT,
    "transferProofUrl" TEXT,
    "paidAt"           TIMESTAMP(3),
    "reminderSentAt"   TIMESTAMP(3),
    "reminderCount"    INTEGER NOT NULL DEFAULT 0,
    "createdBy"        TEXT,
    "createdAt"        TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt"        TIMESTAMP(3) NOT NULL,
    CONSTRAINT "PendingPayment_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "PendingPayment_tenantId_status_idx"
  ON "PendingPayment"("tenantId", "status");
CREATE INDEX "PendingPayment_tenantId_dueDate_idx"
  ON "PendingPayment"("tenantId", "dueDate");

ALTER TABLE "PendingPayment"
  ADD CONSTRAINT "PendingPayment_tenantId_fkey"
  FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE CASCADE;

-- ==================== Lead enrichment ====================

ALTER TABLE "Lead"
  ADD COLUMN "priority"          TEXT NOT NULL DEFAULT 'media',
  ADD COLUMN "internalNotes"     JSONB NOT NULL DEFAULT '[]',
  ADD COLUMN "seenAt"            TIMESTAMP(3),
  ADD COLUMN "lastContactAt"     TIMESTAMP(3),
  ADD COLUMN "experienceId"      TEXT,
  ADD COLUMN "locationId"        TEXT,
  ADD COLUMN "preferredDate"     TIMESTAMP(3),
  ADD COLUMN "numberOfPersons"   INTEGER,
  ADD COLUMN "numberOfAdults"    INTEGER,
  ADD COLUMN "numberOfChildren"  INTEGER,
  ADD COLUMN "budget"            DOUBLE PRECISION,
  ADD COLUMN "message"           TEXT,
  ADD COLUMN "selectedCategory"  TEXT,
  ADD COLUMN "selectedProduct"   TEXT,
  ADD COLUMN "activitiesJson"    JSONB,
  ADD COLUMN "ghlOpportunityId"  TEXT,
  ADD COLUMN "opportunityStatus" TEXT;

CREATE INDEX "Lead_tenantId_priority_idx" ON "Lead"("tenantId", "priority");

-- ==================== Quote enrichment ====================

ALTER TABLE "Quote"
  ADD COLUMN "leadId"               TEXT,
  ADD COLUMN "agentId"               TEXT,
  ADD COLUMN "paymentLinkToken"      TEXT,
  ADD COLUMN "paymentLinkUrl"        TEXT,
  ADD COLUMN "transferProofUrl"      TEXT,
  ADD COLUMN "transferConfirmedAt"   TIMESTAMP(3),
  ADD COLUMN "transferConfirmedBy"   TEXT,
  ADD COLUMN "isAutoGenerated"       BOOLEAN NOT NULL DEFAULT false;

CREATE UNIQUE INDEX "Quote_paymentLinkToken_key"
  ON "Quote"("paymentLinkToken");
CREATE INDEX "Quote_tenantId_leadId_idx" ON "Quote"("tenantId", "leadId");
CREATE INDEX "Quote_tenantId_agentId_idx" ON "Quote"("tenantId", "agentId");

-- Quote.leadId references Lead via SET NULL — preserve quotes if a lead
-- gets deleted (rare but should not cascade-destroy quotes).
ALTER TABLE "Quote"
  ADD CONSTRAINT "Quote_leadId_fkey"
  FOREIGN KEY ("leadId") REFERENCES "Lead"("id")
  ON DELETE SET NULL ON UPDATE CASCADE;

-- ==================== Client enrichment ====================
-- Note: Client already has `dni`, `address`, `cumulativeSpend`, `lifetimeValue`,
-- `totalSpent`, `visitCount`, `lastVisit`. We only add fiscal address parts,
-- tags, and the conversion flag — we deliberately do NOT duplicate the
-- existing spend/visit metrics with renamed columns.

ALTER TABLE "Client"
  ADD COLUMN "nif"          TEXT,
  ADD COLUMN "city"         TEXT,
  ADD COLUMN "postalCode"   TEXT,
  ADD COLUMN "country"      TEXT,
  ADD COLUMN "tags"         JSONB NOT NULL DEFAULT '[]',
  ADD COLUMN "isConverted"  BOOLEAN NOT NULL DEFAULT false;
