import { prisma } from "@/lib/db";
import { logger } from "@/lib/logger";
import { generateDocumentNumber } from "@/lib/documents/numbering";
import { logCrmActivityAsync } from "@/lib/crm/activity-log";

const log = logger.child({ module: "crm/auto-quote" });

type LeadActivities = {
  wantsAccommodation?: boolean;
  wantsForfait?: boolean;
  wantsClases?: boolean;
  wantsEquipment?: boolean;
  // Free-form additional flags survive in Lead.activitiesJson but
  // we only project the four canonical ski services to Quote columns.
  [key: string]: unknown;
};

export type AutoQuoteResult = {
  quoteId: string;
  number: string;
  totalAmount: number;
  itemsAdded: number;
};

/**
 * Generate a draft Quote from a Lead row.
 *
 * Pragmatic MVP — the resulting Quote is a *skeleton* with client info,
 * dates, party size and service flags pulled from the Lead. Total amount
 * is zero and there are no QuoteItems. The admin fills line items via
 * the existing quote-edit UI.
 *
 * Idempotency: if the Lead already has a primary quoteId pointing to an
 * auto-generated quote we return it instead of creating a duplicate.
 */
export async function generateQuoteFromLead(opts: {
  leadId: string;
  tenantId: string;
  /** Sales agent driving the action (admin user). */
  agentId?: string | null;
  agentName?: string | null;
}): Promise<AutoQuoteResult> {
  const { leadId, tenantId } = opts;

  const lead = await prisma.lead.findFirst({
    where: { id: leadId, tenantId },
    select: {
      id: true,
      tenantId: true,
      name: true,
      email: true,
      phone: true,
      ghlContactId: true,
      preferredDate: true,
      numberOfAdults: true,
      numberOfChildren: true,
      activitiesJson: true,
      selectedCategory: true,
      message: true,
      experienceId: true,
      quoteId: true,
    },
  });
  if (!lead) {
    throw new Error(`Lead ${leadId} not found in tenant ${tenantId}`);
  }

  // Idempotency: if the lead has a primary quote and that quote was
  // marked isAutoGenerated, return it.
  if (lead.quoteId) {
    const existing = await prisma.quote.findFirst({
      where: { id: lead.quoteId, tenantId, isAutoGenerated: true },
      select: { id: true, number: true, totalAmount: true },
    });
    if (existing) {
      log.info(
        { leadId, quoteId: existing.id },
        "Auto-quote already exists for lead — returning existing",
      );
      return {
        quoteId: existing.id,
        number: existing.number ?? "",
        totalAmount: existing.totalAmount,
        itemsAdded: 0,
      };
    }
  }

  const activities = (lead.activitiesJson ?? {}) as LeadActivities;

  // Default 1-day stay if preferredDate is set; otherwise use today as a
  // placeholder — admin can adjust.
  const checkIn = lead.preferredDate ?? new Date();
  const checkOut = new Date(checkIn);
  checkOut.setDate(checkOut.getDate() + 1);

  const adults = lead.numberOfAdults ?? 1;
  const children = lead.numberOfChildren ?? 0;
  const destination = lead.selectedCategory ?? "baqueira";

  const number = await generateDocumentNumber(tenantId, "quote", {
    generatedBy: opts.agentId ?? undefined,
    context: "auto_from_lead",
  });

  const quote = await prisma.quote.create({
    data: {
      tenantId,
      number,
      leadId: lead.id,
      agentId: opts.agentId ?? null,
      ghlContactId: lead.ghlContactId,
      clientName: lead.name,
      clientEmail: lead.email ?? null,
      clientPhone: lead.phone ?? null,
      clientNotes: lead.message ?? null,
      destination,
      checkIn,
      checkOut,
      adults,
      children,
      wantsAccommodation: !!activities.wantsAccommodation,
      wantsForfait: !!activities.wantsForfait,
      wantsClases: !!activities.wantsClases,
      wantsEquipment: !!activities.wantsEquipment,
      status: "borrador",
      source: "lead",
      totalAmount: 0,
      isAutoGenerated: true,
    },
    select: { id: true, number: true, totalAmount: true },
  });

  // Update Lead pointers/status (mirrors linkLeadToQuote flow).
  await prisma.lead.update({
    where: { id: lead.id },
    data: {
      quoteId: quote.id,
      status: "calificado",
      convertedAt: new Date(),
    },
  });

  logCrmActivityAsync({
    tenantId,
    entityType: "lead",
    entityId: lead.id,
    action: "converted",
    actorId: opts.agentId ?? null,
    actorName: opts.agentName ?? null,
    details: { quoteId: quote.id, autoGenerated: true },
  });
  logCrmActivityAsync({
    tenantId,
    entityType: "quote",
    entityId: quote.id,
    action: "created",
    actorId: opts.agentId ?? null,
    actorName: opts.agentName ?? null,
    details: { source: "auto_from_lead", leadId: lead.id },
  });

  log.info(
    { leadId, quoteId: quote.id, number, destination, adults, children },
    "Auto-quote generated from lead",
  );

  return {
    quoteId: quote.id,
    number: quote.number ?? number,
    totalAmount: quote.totalAmount,
    itemsAdded: 0,
  };
}
