import { ModuleDefinition } from "./types";

export const MODULE_REGISTRY: Record<string, ModuleDefinition> = {
  core: {
    slug: "core",
    name: "Principal",
    icon: "LayoutDashboard",
    description: "Dashboard, ajustes y equipo",
    dependencies: [],
    isCore: true,
    section: "principal",
    navItems: [
      { label: "Dashboard", href: "/", icon: "LayoutDashboard", permission: null },
      { label: "Ajustes", href: "/settings", icon: "Settings", permission: null, roles: ["Owner / Manager"] },
    ],
    permissions: ["settings:team", "settings:tenant"],
  },
  leads: {
    slug: "leads",
    name: "Leads",
    icon: "Target",
    description: "Captacion, pipeline y scoring de clientes potenciales",
    dependencies: [],
    isCore: false,
    section: "ventas",
    navItems: [
      { label: "Leads", href: "/leads", icon: "Target", permission: null },
    ],
    permissions: ["leads:view", "leads:create", "leads:edit", "leads:delete"],
  },
  crm: {
    slug: "crm",
    name: "CRM",
    icon: "Users",
    description: "Contactos, pipeline y comunicaciones",
    dependencies: [],
    isCore: false,
    section: "ventas",
    navItems: [
      { label: "Contactos", href: "/contacts", icon: "Users", permission: "contacts:view", roles: ["Owner / Manager"] },
      { label: "Pipeline", href: "/pipeline", icon: "Kanban", permission: "pipelines:view", roles: ["Owner / Manager"] },
      { label: "Comunicaciones", href: "/comms", icon: "MessageSquare", permission: "comms:view" },
    ],
    permissions: [
      "contacts:view", "contacts:edit", "contacts:create", "contacts:delete",
      "pipelines:view", "pipelines:edit", "pipelines:create", "pipelines:delete",
      "comms:view", "comms:send", "comms:assign",
    ],
  },
  catalog: {
    slug: "catalog",
    name: "Catalogo",
    icon: "Package",
    description: "Productos, categorias y precios",
    dependencies: [],
    isCore: false,
    section: "ventas",
    navItems: [
      { label: "Catalogo", href: "/catalogo", icon: "Package", permission: null },
    ],
    permissions: ["catalog:view", "catalog:edit"],
  },
  booking: {
    slug: "booking",
    name: "Reservas",
    icon: "CalendarCheck",
    description: "Reservas, presupuestos y operaciones",
    dependencies: ["catalog"],
    isCore: false,
    section: "ventas",
    navItems: [
      { label: "Presupuestos", href: "/presupuestos", icon: "FileText", permission: null, roles: ["Owner / Manager"] },
      { label: "Reservas", href: "/reservas", icon: "CalendarCheck", permission: "reservations:view" },
      { label: "Cancelaciones", href: "/cancellations", icon: "XCircle", permission: null, roles: ["Owner / Manager"] },
      { label: "Operaciones", href: "/operations", icon: "ClipboardList", permission: null, roles: ["Owner / Manager"] },
      { label: "Clientes", href: "/clients", icon: "UserCheck", permission: null },
    ],
    permissions: ["reservations:view", "reservations:create", "reservations:edit"],
  },
  hotel: {
    slug: "hotel",
    name: "Hotel",
    icon: "Building2",
    description: "Habitaciones, tarifas y disponibilidad",
    dependencies: ["booking"],
    isCore: false,
    section: "operaciones",
    navItems: [],
    permissions: ["hotel:view", "hotel:edit", "hotel:manage"],
  },
  spa: {
    slug: "spa",
    name: "Spa",
    icon: "Sparkles",
    description: "Tratamientos, recursos y citas",
    dependencies: ["booking"],
    isCore: false,
    section: "operaciones",
    navItems: [],
    permissions: ["spa:view", "spa:edit", "spa:manage"],
  },
  restaurant: {
    slug: "restaurant",
    name: "Restaurante",
    icon: "UtensilsCrossed",
    description: "Restaurantes, turnos y reservas de mesa",
    dependencies: [],
    isCore: false,
    section: "operaciones",
    navItems: [],
    permissions: ["restaurant:view", "restaurant:edit", "restaurant:manage"],
  },
  operations: {
    slug: "operations",
    name: "Operaciones",
    icon: "ClipboardList",
    description: "Dashboard de operaciones del dia",
    dependencies: [],
    isCore: true,
    section: "operaciones",
    navItems: [
      { label: "Dashboard Operaciones", href: "/operaciones/hoy", icon: "LayoutDashboard", permission: null, roles: ["Owner / Manager"] },
    ],
    permissions: [],
  },
  finance: {
    slug: "finance",
    name: "Finanzas",
    icon: "Receipt",
    description: "Facturas, gastos y transacciones",
    dependencies: [],
    isCore: false,
    section: "gestion",
    navItems: [
      { label: "Finanzas", href: "/finance", icon: "Receipt", permission: null },
      { label: "Nominas", href: "/payroll", icon: "Wallet", permission: null },
    ],
    permissions: ["finance:view", "finance:edit", "finance:manage"],
  },
  suppliers: {
    slug: "suppliers",
    name: "Proveedores",
    icon: "Truck",
    description: "Proveedores, liquidaciones y comisiones",
    dependencies: ["finance"],
    isCore: false,
    section: "gestion",
    navItems: [
      { label: "Proveedores", href: "/suppliers", icon: "Truck", permission: null },
    ],
    permissions: ["suppliers:view", "suppliers:edit", "suppliers:manage"],
  },
  reav: {
    slug: "reav",
    name: "REAV",
    icon: "Scale",
    description: "Regimen especial de agencias de viajes",
    dependencies: ["finance", "suppliers"],
    isCore: false,
    section: "gestion",
    navItems: [
      { label: "REAV", href: "/reav", icon: "Scale", permission: null },
    ],
    permissions: ["reav:view", "reav:edit"],
  },
  tpv: {
    slug: "tpv",
    name: "TPV",
    icon: "CreditCard",
    description: "Punto de venta, cajas y tickets",
    dependencies: ["finance"],
    isCore: false,
    section: "gestion",
    navItems: [
      { label: "Punto de Venta", href: "/tpv/venta", icon: "CreditCard", permission: null },
      { label: "Backoffice TPV", href: "/tpv", icon: "ClipboardList", permission: null, roles: ["Owner / Manager"] },
    ],
    permissions: ["tpv:view", "tpv:operate", "tpv:manage"],
  },
  storefront: {
    slug: "storefront",
    name: "Tienda Online",
    icon: "ShoppingCart",
    description: "Web publica, carrito y checkout",
    dependencies: ["catalog"],
    isCore: false,
    section: "online",
    navItems: [
      { label: "Tienda Online", href: "/storefront", icon: "ShoppingCart", permission: null },
    ],
    permissions: ["storefront:view", "storefront:edit"],
  },
  cms: {
    slug: "cms",
    name: "Contenidos",
    icon: "PanelsTopLeft",
    description: "Paginas, slideshow y menus",
    dependencies: [],
    isCore: false,
    section: "online",
    navItems: [
      { label: "Contenidos", href: "/cms", icon: "PanelsTopLeft", permission: null },
    ],
    permissions: ["cms:view", "cms:edit"],
  },
  ticketing: {
    slug: "ticketing",
    name: "Ticketing",
    icon: "Ticket",
    description: "Cupones, plataformas y canje",
    dependencies: ["booking"],
    isCore: false,
    section: "ventas",
    navItems: [
      { label: "Ticketing", href: "/ticketing", icon: "Ticket", permission: null },
    ],
    permissions: ["ticketing:view", "ticketing:edit", "ticketing:manage"],
  },
  reviews: {
    slug: "reviews",
    name: "Reseñas",
    icon: "Star",
    description: "Reseñas y valoraciones de clientes",
    dependencies: [],
    isCore: false,
    section: "online",
    navItems: [
      { label: "Reseñas", href: "/reviews", icon: "Star", permission: null },
    ],
    permissions: ["reviews:view", "reviews:moderate"],
  },
  packs: {
    slug: "packs",
    name: "Packs",
    icon: "Boxes",
    description: "Packs compuestos (hotel + experiencias + restaurante)",
    dependencies: ["catalog", "booking"],
    isCore: false,
    section: "ventas",
    navItems: [
      { label: "Packs", href: "/packs", icon: "Boxes", permission: null },
    ],
    permissions: ["packs:view", "packs:edit"],
  },
  instructors: {
    slug: "instructors",
    name: "Escuela",
    icon: "GraduationCap",
    description: "Escuela de esqui: profesores, planning, fichaje, diplomas",
    dependencies: ["booking"],
    isCore: false,
    section: "operaciones",
    navItems: [
      { label: "Resumen", href: "/profesores/overview", icon: "LayoutDashboard", permission: null, roles: ["Owner / Manager"] },
      { label: "Profesores", href: "/profesores", icon: "GraduationCap", permission: null, roles: ["Owner / Manager"] },
      { label: "Planning", href: "/profesores/planning", icon: "CalendarCog", permission: null, roles: ["Owner / Manager"] },
      { label: "Horario", href: "/profesores/horario", icon: "Calendar", permission: null, roles: ["Owner / Manager"] },
      { label: "Fichaje", href: "/profesores/fichaje", icon: "Clock", permission: null, roles: ["Owner / Manager"] },
      { label: "Incidencias", href: "/profesores/incidencias", icon: "AlertTriangle", permission: null, roles: ["Owner / Manager"] },
      { label: "Diplomas", href: "/profesores/diplomas", icon: "Award", permission: null, roles: ["Owner / Manager"] },
      { label: "Amonestaciones", href: "/profesores/amonestaciones", icon: "ShieldAlert", permission: null, roles: ["Owner / Manager"] },
      { label: "KPIs", href: "/profesores/kpis", icon: "BarChart3", permission: null, roles: ["Owner / Manager"] },
    ],
    permissions: ["instructors:view", "instructors:edit", "instructors:manage"],
  },
  rental: {
    slug: "rental",
    name: "Alquiler",
    icon: "Snowflake",
    description: "Inventario de equipos, pedidos de alquiler y perfiles de tallas",
    dependencies: ["booking"],
    isCore: false,
    section: "operaciones",
    navItems: [
      { label: "Alquiler", href: "/alquiler", icon: "Snowflake", permission: null },
    ],
    permissions: ["rental:view", "rental:edit", "rental:manage"],
  },
};

export const ALL_MODULE_SLUGS = Object.keys(MODULE_REGISTRY);

export const SECTION_ORDER: Record<string, { label: string; order: number }> = {
  principal: { label: "Principal", order: 0 },
  ventas: { label: "Ventas", order: 1 },
  operaciones: { label: "Operaciones", order: 2 },
  gestion: { label: "Gestion", order: 3 },
  online: { label: "Online", order: 4 },
};
